<?php
/**
 * @file
 * Lazy page generation module.
 *
 * @author: Frédéric G. MARAND <fgm@osinet.fr>
 *
 * @copyright (c) 2015 Ouest Systèmes Informatiques (OSInet).
 *
 * @license General Public License version 2 or later
 */

use Drupal\xautoload\Adapter\LocalDirectoryAdapter;
use OSInet\Lazy\Controller\Controller;
use OSInet\Lazy\Route;
use OSInet\Lazy\Router;
use OSInet\Lazy\Variable;

/**
 * Controller for overridden routes.
 *
 * @param string $original_controller
 * @param Route $route
 *
 * @return mixed|string
 */
function lazy_controller_override($original_controller, Route $route) {
  $args = array_slice(func_get_args(), 2);
  $controller = Controller::create($route, $original_controller, $args);
  $ret = $controller->build($args);
  return $ret;
}

/**
 * Implements hook_cron_queue_info().
 */
function lazy_cron_queue_info() {
  return Controller::cronQueueInfo();
}

/**
 * Implements hook_menu_alter().
 */
function lazy_menu_alter(&$default_routes) {
  $requested_routes = Variable::get('routes');
  $router = new Router($default_routes, $requested_routes);
  $actual_routes = $router->alteredRoutes();

  foreach ($actual_routes as $name => $info) {
    $default_routes[$name] = $info;
  }
}

/**
 * Implements hook_permission().
 */
function lazy_permission() {
  return Controller::permission();
}

/**
 * Implements hook_xautoload().
 */
function lazy_xautoload(LocalDirectoryAdapter $adapter) {
  $adapter->absolute()->addPsr4('OSInet\Lazy\\', __DIR__ . '/lib/OSInet/Lazy');
}
